### ISSUE TITLE
Error when broadcasting composed functions

### ISSUE THREAD

**Issue by chrstphrbrns** [JuliaGPU/CUDA.jl#1550]
```julia
               _
   _       _ _(_)_     |  Documentation: https://docs.julialang.org
  (_)     | (_) (_)    |
   _ _   _| |_  __ _   |  Type "?" for help, "]?" for Pkg help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 1.9.0-DEV.848 (2022-06-24)
 _/ |\__'_|_|_|\__'_|  |  Commit 51c88129e2 (1 day old master)
|__/                   |

julia> using CUDA

julia> a = CUDA.randn(100_000);

julia> @time sum((sin∘cos∘sin∘cos∘sin∘cos∘sin∘cos).(a))
ERROR: GPU broadcast resulted in non-concrete element type Any.
This probably means that the function you are broadcasting contains an error or type instability.
...

julia> @time sum((sin∘cos∘sin).(a))
ERROR: GPU broadcast resulted in non-concrete element type Any.
This probably means that the function you are broadcasting contains an error or type instability.
...
```
```julia
   _       _ _(_)_     |  Documentation: https://docs.julialang.org
  (_)     | (_) (_)    |
   _ _   _| |_  __ _   |  Type "?" for help, "]?" for Pkg help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 1.9.0-DEV.848 (2022-06-24)
 _/ |\__'_|_|_|\__'_|  |  Commit 51c88129e2 (1 day old master)
|__/                   |

julia> using CUDA

julia> a = CUDA.randn(100_000);

julia> @time sum((sin∘cos).(a))
  4.605380 seconds (11.41 M allocations: 775.927 MiB, 6.96% gc time, 60.82% compilation time)
53347.61f0

julia> @time sum((sin∘cos∘sin).(a))
  0.868966 seconds (2.06 M allocations: 139.620 MiB, 5.15% gc time, 79.97% compilation time)
70603.82f0
```

The final ```sin∘cos∘sin``` command fails in the first example and succeeds in the second

```
CUDA toolkit 11.7, artifact installation
NVIDIA driver 510.73.5, for CUDA 11.6
CUDA driver 11.6

Libraries: 
- CUBLAS: 11.10.1
- CURAND: 10.2.10
- CUFFT: 10.7.2
- CUSOLVER: 11.3.5
- CUSPARSE: 11.7.3
- CUPTI: 17.0.0
- NVML: 11.0.0+510.73.5
- CUDNN: 8.30.2 (for CUDA 11.5.0)
- CUTENSOR: 1.4.0 (for CUDA 11.5.0)

Toolchain:
- Julia: 1.9.0-DEV.848
- LLVM: 14.0.5
- PTX ISA support: 3.2, 4.0, 4.1, 4.2, 4.3, 5.0, 6.0, 6.1, 6.3, 6.4, 6.5, 7.0, 7.1, 7.2, 7.3, 7.4, 7.5
- Device capability support: sm_35, sm_37, sm_50, sm_52, sm_53, sm_60, sm_61, sm_62, sm_70, sm_72, sm_75, sm_80, sm_86

2 devices:
  0: NVIDIA GeForce RTX 2080 Ti (sm_75, 10.098 GiB / 11.000 GiB available)
  1: NVIDIA GeForce RTX 2080 Ti (sm_75, 10.753 GiB / 11.000 GiB available)
```
