### ISSUE TITLE
CUDA test fails

### ISSUE THREAD

**Issue by scaballero** [JuliaGPU/CUDA.jl#1660]
test suite and using CUDA does not work

**To reproduce**

```
]test CUDA
```

**Expected behavior**

test passed

**Version info**

Details on Julia:

```
Julia Version 1.8.1
Commit afb6c60d69a (2022-09-06 15:09 UTC)
Platform Info:
  OS: Linux (x86_64-linux-gnu)
  CPU: 32 × Intel(R) Xeon(R) Gold 6134 CPU @ 3.20GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-13.0.1 (ORCJIT, skylake-avx512)
  Threads: 16 on 32 virtual cores
Environment:
  LD_LIBRARY_PATH = /opt/intel/oneapi/vpl/2022.2.0/lib:/opt/intel/oneapi/tbb/2021.7.0/env/../lib/intel64/gcc4.8:/opt/intel/oneapi/mpi/2021.7.0//libfabric/lib:/opt/intel/oneapi/mpi/2021.7.0//lib/release:/opt/intel/oneapi/mpi/2021.7.0//lib:/opt/intel/oneapi/mkl/2022.2.0/lib/intel64:/opt/intel/oneapi/itac/2021.7.0/slib:/opt/intel/oneapi/ippcp/2021.6.1/lib/intel64:/opt/intel/oneapi/ipp/2021.6.1/lib/intel64:/opt/intel/oneapi/dnnl/2022.2.0/cpu_dpcpp_gpu_dpcpp/lib:/opt/intel/oneapi/debugger/2021.7.0/gdb/intel64/lib:/opt/intel/oneapi/debugger/2021.7.0/libipt/intel64/lib:/opt/intel/oneapi/debugger/2021.7.0/dep/lib:/opt/intel/oneapi/dal/2021.7.0/lib/intel64:/opt/intel/oneapi/compiler/2022.2.0/linux/lib:/opt/intel/oneapi/compiler/2022.2.0/linux/lib/x64:/opt/intel/oneapi/compiler/2022.2.0/linux/lib/oclfpga/host/linux64/lib:/opt/intel/oneapi/compiler/2022.2.0/linux/compiler/lib/intel64_lin:/opt/intel/oneapi/ccl/2021.7.0/lib/cpu_gpu_dpcpp:/usr/local/cuda-11.8/lib64
  JULIA_NUM_THREADS = 16
Details on CUDA:
11.8
```

```
CUDA toolkit 11.6, artifact installation
NVIDIA driver 520.61.5, for CUDA 11.8
CUDA driver 11.8

Libraries: 
- CUBLAS: 11.8.1
- CURAND: 10.2.9
- CUFFT: 10.7.0
- CUSOLVER: 11.3.2
- CUSPARSE: 11.7.1
- CUPTI: 16.0.0
- NVML: 11.0.0+520.61.5
- CUDNN: 8.30.2 (for CUDA 11.5.0)
- CUTENSOR: 1.4.0 (for CUDA 11.5.0)

Toolchain:
- Julia: 1.8.1
- LLVM: 13.0.1
- PTX ISA support: 3.2, 4.0, 4.1, 4.2, 4.3, 5.0, 6.0, 6.1, 6.3, 6.4, 6.5, 7.0
- Device capability support: sm_35, sm_37, sm_50, sm_52, sm_53, sm_60, sm_61, sm_62, sm_70, sm_72, sm_75, sm_80

2 devices:
  0: Quadro RTX 5000 (sm_75, 15.739 GiB / 16.000 GiB available)
  1: Quadro P6000 (sm_61, 23.851 GiB / 24.000 GiB available)
```
