### ISSUE TITLE
Broadcast does not preserve buffer type

### ISSUE THREAD

**Issue by kmp5VT** [JuliaGPU/CUDA.jl#2191]
**Describe the bug**

Some operations to CuArrays convert `UnifiedBuffer` arrays to `DeviceBuffer`

**To reproduce**

```
 using CUDA
 
 v = CUDA.CuVector{Float32, CUDA.Mem.UnifiedBuffer}(undef, 20)
 fill!(v, 2.0)
 one(Float32) * v = 20-element CuArray{Float32, 1, CUDA.Mem.DeviceBuffer}:
```
 

**Version info**

Details on Julia:

```
Julia Version 1.9.4
 Commit 8e5136fa297 (2023-11-14 08:46 UTC)
 Build Info:
   Official https://julialang.org/ release
 Platform Info:
   OS: Linux (x86_64-linux-gnu)
   CPU: 32 × Intel(R) Xeon(R) Gold 6244 CPU @ 3.60GHz
   WORD_SIZE: 64
   LIBM: libopenlibm
   LLVM: libLLVM-14.0.6 (ORCJIT, cascadelake)
   Threads: 1 on 32 virtual cores
```

Details on CUDA:

```
CUDA runtime 12.3, artifact installation
 CUDA driver 12.3
 NVIDIA driver 535.113.1, originally for CUDA 12.2
 
 CUDA libraries: 
 - CUBLAS: 12.3.4
 - CURAND: 10.3.4
 - CUFFT: 11.0.12
 - CUSOLVER: 11.5.4
 - CUSPARSE: 12.2.0
 - CUPTI: 21.0.0
 - NVML: 12.0.0+535.113.1
 
 Julia packages: 
 - CUDA: 5.1.1
 - CUDA_Driver_jll: 0.7.0+0
 - CUDA_Runtime_jll: 0.10.1+0
 
 Toolchain:
 - Julia: 1.9.4
 - LLVM: 14.0.6
 
 1 device:
   0: NVIDIA RTX A6000 (sm_86, 45.700 GiB / 47.988 GiB available).

```
