### ISSUE TITLE
LLVM WMMA errors 

### ISSUE THREAD

**Issue by shrimpceviche** [JuliaGPU/CUDA.jl#380]
**Describe the bug**

I encountered the following errors while executing the test suite ```Pkg.test("CUDA") ```
``` LLVM error: Cannot select: intrinsic %llvm.nvvm.wmma.m16n16k16.load.c.col.stride.f32
 LLVM error: Cannot select: intrinsic %llvm.nvvm.wmma.m16n16k16.load.c.col.stride.f16
 LLVM error: Cannot select: intrinsic %llvm.nvvm.wmma.m16n16k16.store.d.row.stride.f16
 LLVM error: Cannot select: intrinsic %llvm.nvvm.wmma.m16n16k16.store.d.row.stride.f32
 LLVM error: Cannot select: intrinsic %llvm.nvvm.wmma.m16n16k16.store.d.col.stride.f16
 LLVM error: Cannot select: intrinsic %llvm.nvvm.wmma.m16n16k16.store.d.col.stride.f32
```

**To reproduce**

The Minimal Working Example (MWE) for this bug:

```julia
using CUDA, Pkg
Pkg.test("CUDA")
```

<details><summary>Manifest.toml</summary>
<p>

```
CUDA.jl v1.3
```

</p>
</details>

**Expected behavior**

All the tests should pass

**Version info**

Details on Julia:

```
Julia Version 1.5.0
Commit 96786e22cc (2020-08-01 23:44 UTC)        
Platform Info:
  OS: Windows (x86_64-w64-mingw32)
  CPU: Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz
  WORD_SIZE: 64    
  LIBM: libopenlibm
  LLVM: libLLVM-9.0.1 (ORCJIT, skylake)
Environment:
  JULIA_EDITOR = "C:\Users\Jack\AppData\Local\atom\app-1.50.0\atom.exe"  -a
  JULIA_HOME = C:\Users\Jack\AppData\Local\Programs\Julia 1.5.0\bin        
  JULIA_NUM_THREADS = 4
```

Details on CUDA:

```
# please post the output of:
CUDA toolkit 11.0.3, artifact installation
CUDA driver 11.0.0

Libraries:        
- CUBLAS: 11.2.0
- CURAND: 10.2.1
- CUFFT: 10.2.1
- CUSOLVER: 10.6.0
- CUSPARSE: 11.1.1
- CUPTI: 13.0.0   
- NVML: missing   
- CUDNN: 8.0.2 (for CUDA 11.0.0)   
- CUTENSOR: 1.2.0 (for CUDA 11.0.0)

Toolchain:
- Julia: 1.5.0
- LLVM: 9.0.1
- PTX ISA support: 3.2, 4.0, 4.1, 4.2, 4.3, 5.0, 6.0, 6.1, 6.3, 6.4
- Device support: sm_35, sm_37, sm_50, sm_52, sm_53, sm_60, sm_61, sm_62, sm_70, sm_72, sm_75

1 device: 
GTX 1050
```

**Additional context**

**Comment by maleadt** [comment]
Which exact test fails? And can you post `capability(device())` and `CUDA.supported_capability(device())`?

**Comment by GregPlowman** [comment]
I'm getting the same errors. Well I think so, the error trace messages are very long and scroll off the screen.

Windows 10, Julia v1.5.0, CUDA v1.3.0

`capability(device())` and `CUDA.supported_capability(device())` both return `v"6.1.0"`.

Does `wmma` require >= `v"7.0"`?
If so, then presumably `wmma` is not supported on this gpu and these tests are meant to be skipped?

Commenting out line 181 of `runtests.jl`
```
filter!(in(tests), skip_tests) # only skip tests that we were going to run
```
does indeed result in `wmma` tests being skipped:
```
[ Info: Skipping the following tests: cutensor, device\wmma
```

Output from `CUDA.versioninfo()`

```
CUDA toolkit 11.0.3, artifact installation
CUDA driver 11.0.0
NVIDIA driver 452.6.0

Libraries:
- CUBLAS: 11.2.0
- CURAND: 10.2.1
- CUFFT: 10.2.1
- CUSOLVER: 10.6.0
- CUSPARSE: 11.1.1
- CUPTI: 13.0.0
- NVML: 11.0.0+452.6
- CUDNN: 8.0.2 (for CUDA 11.0.0)
- CUTENSOR: 1.2.0 (for CUDA 11.0.0)

Toolchain:
- Julia: 1.5.0
- LLVM: 9.0.1
- PTX ISA support: 3.2, 4.0, 4.1, 4.2, 4.3, 5.0, 6.0, 6.1, 6.3, 6.4
- Device support: sm_35, sm_37, sm_50, sm_52, sm_53, sm_60, sm_61, sm_62, sm_70, sm_72, sm_75

2 devices:
  0: GeForce GTX 1080 (sm_61, 7.591 GiB / 8.000 GiB available)
  1: GeForce GTX 1080 (sm_61, 7.192 GiB / 8.000 GiB available)
```
