### ISSUE TITLE
Memory allocation fails for multi-GPU

### ISSUE THREAD

**Issue by MGYamada** [JuliaGPU/CUDA.jl#943]
**Describe the bug**

This only happens in multi-GPU.
Memory allocation fails for the second GPU (sub-A100) while there is a plenty of room.
This does not occur in v2.6.3, so maybe it is a bug of the latest version.

**To reproduce**

```julia
using CUDA
device!(1)
CUDA.rand(100)
```
```
ERROR: Out of GPU memory trying to allocate 400 bytes
Effective GPU memory usage: 1.05% (424.000 MiB/39.586 GiB)
CUDA allocator usage: 0 bytes
Memory pool usage: 0 bytes (0 bytes allocated, 0 bytes cached)

Stacktrace:
  [1] #alloc#195
    @ ~/.julia/packages/CUDA/KSOGO/src/pool.jl:266 [inlined]
  [2] alloc
    @ ~/.julia/packages/CUDA/KSOGO/src/pool.jl:258 [inlined]
  [3] CuArray{Float32, 1}(#unused#::UndefInitializer, dims::Tuple{Int64})
    @ CUDA ~/.julia/packages/CUDA/KSOGO/src/array.jl:20
  [4] CuArray
    @ ~/.julia/packages/CUDA/KSOGO/src/array.jl:101 [inlined]
  [5] rand
    @ ~/.julia/packages/CUDA/KSOGO/lib/curand/random.jl:149 [inlined]
  [6] #rand#95
    @ ~/.julia/packages/CUDA/KSOGO/lib/curand/random.jl:159 [inlined]
  [7] rand
    @ ~/.julia/packages/CUDA/KSOGO/lib/curand/random.jl:159 [inlined]
  [8] rand(::Int64)
    @ CUDA ~/.julia/packages/CUDA/KSOGO/src/random.jl:155
  [9] top-level scope
    @ REPL[3]:1
 [10] top-level scope
    @ ~/.julia/packages/CUDA/KSOGO/src/initialization.jl:52
```

I am using the master branch of CUDA.jl.

**Expected behavior**

Just allocate random numbers.

**Version info**

Details on Julia:

```
Julia Version 1.6.1
Commit 6aaedecc44 (2021-04-23 05:59 UTC)
Platform Info:
  OS: Linux (x86_64-redhat-linux)
  CPU: Intel(R) Xeon(R) Gold 6238R CPU @ 2.20GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-11.0.1 (ORCJIT, cascadelake)
```

Details on CUDA:

```
CUDA toolkit 11.3.0, artifact installation
CUDA driver 11.2.0
NVIDIA driver 460.32.3

Libraries: 
- CUBLAS: 11.4.2
- CURAND: 10.2.4
- CUFFT: 10.4.2
- CUSOLVER: 11.1.1
- CUSPARSE: 11.5.0
- CUPTI: 14.0.0
- NVML: 11.0.0+460.32.3
- CUDNN: 8.20.0 (for CUDA 11.3.0)
- CUTENSOR: 1.3.0 (for CUDA 11.2.0)

Toolchain:
- Julia: 1.6.1
- LLVM: 11.0.1
- PTX ISA support: 3.2, 4.0, 4.1, 4.2, 4.3, 5.0, 6.0, 6.1, 6.3, 6.4, 6.5, 7.0
- Device capability support: sm_35, sm_37, sm_50, sm_52, sm_53, sm_60, sm_61, sm_62, sm_70, sm_72, sm_75, sm_80

2 devices:
  0: A100-PCIE-40GB (sm_80, 39.583 GiB / 39.586 GiB available)
  1: A100-PCIE-40GB (sm_80, 38.908 GiB / 39.586 GiB available)
```
