### ISSUE TITLE
Integer division error for the product of sparse times empty matrices

### ISSUE THREAD

**Issue by MGYamada** [JuliaGPU/CUDA.jl#962]
**Describe the bug**

The product of a sparse matrix times a zero-sized matrix produces an error.

**To reproduce**

The Minimal Working Example (MWE) for this bug:

```julia
using CUDA
using SparseArrays
A = sprand(10, 10, 0.1)
B = zeros(10, 0)
A * B # OK
CUSPARSE.CuSparseMatrixCSC(A) * CuArray(B) # Error
```

```
ERROR: DivideError: integer division error
Stacktrace:
  [1] macro expansion
    @ ~/.julia/packages/CUDA/e3lyC/lib/cusparse/libcusparse.jl:5011 [inlined]
  [2] macro expansion
    @ ~/.julia/packages/CUDA/e3lyC/src/pool.jl:402 [inlined]
  [3] macro expansion
    @ ~/.julia/packages/CUDA/e3lyC/lib/cusparse/error.jl:39 [inlined]
  [4] cusparseCreateDnMat(dnMatDescr::Base.RefValue{Ptr{Nothing}}, rows::Int64, cols::Int64, ld::Int64, values::CuArray{Float64, 2}, valueType::Type, order::CUDA.CUSPARSE.cusparseOrder_t)
    @ CUDA.CUSPARSE ~/.julia/packages/CUDA/e3lyC/lib/utils/call.jl:26
  [5] CuDenseMatrixDescriptor
    @ ~/.julia/packages/CUDA/e3lyC/lib/cusparse/generic.jl:27 [inlined]
  [6] mm!(transa::Char, transb::Char, alpha::Bool, A::CUDA.CUSPARSE.CuSparseMatrixCSC{Float64}, B::CuArray{Float64, 2}, beta::Bool, C::CuArray{Float64, 2}, index::Char)
    @ CUDA.CUSPARSE ~/.julia/packages/CUDA/e3lyC/lib/cusparse/generic.jl:191
  [7] mm_wrapper(transa::Char, transb::Char, alpha::Bool, A::CUDA.CUSPARSE.CuSparseMatrixCSC{Float64}, B::CuArray{Float64, 2}, beta::Bool, C::CuArray{Float64, 2})
    @ CUDA.CUSPARSE ~/.julia/packages/CUDA/e3lyC/lib/cusparse/interfaces.jl:17
  [8] mul!
    @ ~/.julia/packages/CUDA/e3lyC/lib/cusparse/interfaces.jl:66 [inlined]
  [9] mul!
    @ ~/julia/usr/share/julia/stdlib/v1.6/LinearAlgebra/src/matmul.jl:275 [inlined]
 [10] *(A::CUDA.CUSPARSE.CuSparseMatrixCSC{Float64}, B::CuArray{Float64, 2})
    @ LinearAlgebra ~/julia/usr/share/julia/stdlib/v1.6/LinearAlgebra/src/matmul.jl:153
 [11] top-level scope
    @ REPL[265]:1
```

I am using the master branch.

**Expected behavior**

An empty 10x0 matrix should be produced.

**Version info**

Details on Julia:

```
Julia Version 1.6.1
Commit 6aaedecc44 (2021-04-23 05:59 UTC)
Platform Info:
  OS: Linux (x86_64-redhat-linux)
  CPU: Intel(R) Xeon(R) Gold 6238R CPU @ 2.20GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-11.0.1 (ORCJIT, cascadelake)
```

Details on CUDA:

```
CUDA toolkit 11.3.1, artifact installation
CUDA driver 11.3.0
NVIDIA driver 465.19.1

Libraries: 
- CUBLAS: 11.5.1
- CURAND: 10.2.4
- CUFFT: 10.4.2
- CUSOLVER: 11.1.2
- CUSPARSE: 11.6.0
- CUPTI: 14.0.0
- NVML: 11.0.0+465.19.1
- CUDNN: 8.20.0 (for CUDA 11.3.0)
- CUTENSOR: 1.3.0 (for CUDA 11.2.0)

Toolchain:
- Julia: 1.6.1
- LLVM: 11.0.1
- PTX ISA support: 3.2, 4.0, 4.1, 4.2, 4.3, 5.0, 6.0, 6.1, 6.3, 6.4, 6.5, 7.0
- Device capability support: sm_35, sm_37, sm_50, sm_52, sm_53, sm_60, sm_61, sm_62, sm_70, sm_72, sm_75, sm_80

2 devices:
  0: NVIDIA A100-PCIE-40GB (sm_80, 39.151 GiB / 39.586 GiB available)
  1: NVIDIA A100-PCIE-40GB (sm_80, 39.583 GiB / 39.586 GiB available)
```
